config/routes.rb
Rails.application.routes.draw do
  resources :groups
 
  devise_for :users

  get'/login' => 'groups#login'

  root to: "groups#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
    
    def login
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
 
      params.require(:group).permit(:name, :description)

      params.require(:group).permit(:name, :area_id, :average_age, :pr_text, :match_log_id, :time_id, :rate)
 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
  　 <%= f.label "グループ名" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :area_id, '地域' %><br />
    <%= f.select :area_id, ['北海道','青森','岩手','秋田','宮城','山形','宮城','福島','新潟','栃木','茨城','群馬','千葉','東京','埼玉','神奈川','長野','富山','石川','岐阜','福井','山梨','静岡','愛知','滋賀','三重','京都','奈良','大阪','和歌山','兵庫','鳥取','岡山','広島','島根','山口','香川','徳島','高知','愛媛','大分','福岡','佐賀','長崎','熊本','宮崎','鹿児島','沖縄'
      ] %>
  </div>
  <div class="field">
    <%= f.label "グループPR" %><br>
    <%= f.text_field :pr_text %>
  </div>
  <div class="field">
    <%= f.label "マッチングID" %><br>
    <%= f.number_field :match_log_id %>
  </div>
  <div class="field">
    <%= f.label "希望時間" %><br>
    <%= f.select :time_id, ['17:00~', '18:00~', '19:00~', '20:00~'] %>
  </div>
  <div class="actions">
    <%= f.submit "グループ作成" %>
 
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

 
<h1>Listing Groups</h1>

<h1>グループリスト</h1>
 

<table>
  <thead>
    <tr>
 
      <th>Name</th>
      <th>Description</th>

      <th>名前</th>
      <th>地域</th>
      <th>平均年齢</th>
      <th>グループPR</th>
      <th>マッチングID</th>
      <th>時間</th>
      <th>評価</th>
 
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
 
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <td><%= group.area_id %></td>
        <td><%= group.average_age %></td>
        <td><%= group.pr_text %></td>
        <td><%= group.match_log_id %></td>
        <td><%= group.time_id %></td>
        <td><%= group.rate %></td>
        <td><%= link_to '詳細', group %></td>
        <td><%= link_to '編集', edit_group_path(group) %></td>
        <td><%= link_to '削除', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規グループ作成', new_group_path %>
 

app/views/groups/login.html.erb
<p>ログインID</p>
<p>パスワード</p>

app/views/groups/new.html.erb
 

<h1>グループ登録</h1>

<%= render 'form' %>

<%= link_to '戻る', groups_path %>
 

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <strong>Name:</strong>

  <strong>グループ名前</strong>
  <%= @group.name %>
</p>

<p>

  <strong>Description:</strong>
  
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>
  <strong>地域</strong>
  <%= @group.area_id %>
</p>

<p>
  <strong>平均年齢</strong>
  <%= @group.average_age %>
</p>

<p>
  <strong>自己PR</strong>
  <%= @group.pr_text %>
</p>

<p>
  <strong>マッチングID</strong>
  <%= @group.match_log_id %>
</p>

<p>
  <strong>希望時間帯</strong>
  <%= @group.time_id %>
</p>

<p>
  <strong>評価</strong>
  <%= @group.rate %>
</p>

<%= link_to '編集', edit_group_path(@group) %> |
<%= link_to '戻る', groups_path %>

app/views/home/top.html.erb
welcome

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GouconCupid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
    <% if user_signed_in? %> 
      <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
      <!-- *_path はUserモデルを作成したときに、
        deviseにより自動で作成されてますので、rake routesで確認できます -->
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'プロフィール変更', edit_user_registration_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "サインイン", new_user_registration_path %> |
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </nav>
</header>

<%= yield %>

</body>
</html>